Increment13
aashmak/gometric pull request #13
Opened 2023-04-20 19:50 UTC by aashmak

2023-04-22 16:43 UTC, edylcrm requested changes

2023-04-22 16:43 UTC, edylcrm commented on internal/agent/collector.go
> +	if response.Header.Get("Content-Encoding") == "gzip" {
Content-Encoding может содержать несколько значений через запятую.
Пример: Content-Encoding: deflate, gzip
В таком случае этот if будет работать не правильно
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

2023-04-22 16:43 UTC, edylcrm commented on internal/logger/logger.go
> +func NewLogger(level string, logFile string) {
Для пет проекта логи можно писать в файл, но стоит помнить, что лучше их писать в stdout.
https://12factor.net/ru/logs

2023-04-22 16:43 UTC, edylcrm commented on internal/memstorage/memstorage.go
> +func (m *MemStorage) Open() error {
Мне не особо нравится, что есть отдельно два метода по установки filename и его чтению. При использовании этого функционала можно сделать ошибку. Я бы это объединил в один метод.

2023-04-22 16:43 UTC, edylcrm commented on internal/memstorage/memstorage.go
> +func (m *MemStorage) Get(k string) (interface{}, error) {
И я бы все таки избегал использование interface{} в коде

2023-04-22 16:43 UTC, edylcrm commented on internal/memstorage/memstorage.go
> +	file, err := os.OpenFile(m.StoreFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0777)
Выше уже открывается файл, лучше использовать для записи его. Открывать файл на чтение не дешевая операция и делать это на каждый вызов метода может приводить к деградации на большом кол-ве запросов.

2023-04-22 16:43 UTC, edylcrm commented on internal/metrics/metrics.go
> +		if m.Value != nil {
Можно написать короче:
```
if m.Value == nil {
    return nil, fmt.Errorf("invalid value")
}
message = []byte(fmt.Sprintf("%s:gauge:%f", m.ID, *m.Value))
```

2023-04-22 16:43 UTC, edylcrm commented on internal/postgres/postgres.go
> +	poolConfig, err := pgxpool.ParseConfig(p.DSN)
Вообще структура которой нужно ходить в БД не должна создавать соединение, а получать его уже сконфигурированным.
Могут быть много структур которым нужно ходить в эту же БД и создавать каждый раз коннект будет не оптимально. Тем более что внутри коннект использует пул соединений

2023-04-22 16:43 UTC, edylcrm commented on internal/postgres/postgres.go
> +func (p *Postgres) Open() error {
И так же если забыть вызвать метод Open() то можно получить ошибку

2023-04-22 16:43 UTC, edylcrm commented on internal/postgres/postgres.go
> +	switch vtype {
```
switch v.(type) {}
```

2023-04-22 16:43 UTC, edylcrm commented on internal/postgres/postgres.go
> +		switch vtype {
v.(type)

2023-04-24 18:26 UTC, aashmak commented on internal/agent/collector.go
> +	if response.Header.Get("Content-Encoding") == "gzip" {
исправлено, добавлена функция:
func contentEncodingContains(a []string, x string) bool {}

2023-04-24 18:26 UTC, aashmak commented on internal/logger/logger.go
> +func NewLogger(level string, logFile string) {
по-умолчанию (если файл не задан) лог пишется в stdout

2023-04-24 18:27 UTC, aashmak commented on internal/memstorage/memstorage.go
> +func (m *MemStorage) Open() error {
удалил функцию SetStoreFile()

2023-04-24 18:27 UTC, aashmak commented on internal/memstorage/memstorage.go
> +	file, err := os.OpenFile(m.StoreFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0777)
исправлено.

2023-04-24 18:27 UTC, aashmak commented on internal/metrics/metrics.go
> +		if m.Value != nil {
исправлено

2023-04-24 18:28 UTC, aashmak commented on internal/postgres/postgres.go
> +	poolConfig, err := pgxpool.ParseConfig(p.DSN)
исправлено.

pgxpool.ParseConfig(dsn) вызывается вне структуры, далее указатель передается в структуру

2023-04-24 18:29 UTC, aashmak commented on internal/postgres/postgres.go
> +func (p *Postgres) Open() error {
удалил метод Open() за ненадобностью

2023-04-24 18:30 UTC, aashmak commented on internal/postgres/postgres.go
> +	switch vtype {
исправлено

2023-04-24 18:30 UTC, aashmak commented on internal/postgres/postgres.go
> +		switch vtype {
исправлено

2023-04-24 18:32 UTC, aashmak commented on internal/memstorage/memstorage.go
> +func (m *MemStorage) Get(k string) (interface{}, error) {
Согласен. В будущем, вероятно так делать не стану, по примеру других библиотек, например, redis, можно возвращать в ответе структуру и к ней уже применять методы Int(), String(), Float64() и тд.

2023-04-24 18:57 UTC, edylcrm commented on internal/logger/logger.go
> +func NewLogger(level string, logFile string) {
Это просто чтобы понимать как лучше делать в прод приложениях :)

2023-04-24 18:58 UTC, edylcrm approved these changes

2023-08-16 18:24 UTC, merged